import { InstrumentPreset } from '../types/instrument';

export const BUILT_IN_PRESETS: InstrumentPreset[] = [
  // PIANO PRESETS
  {
    id: 'concert-piano',
    name: 'Concert Piano',
    instrumentId: 'acoustic-piano',
    category: 'Piano',
    isBuiltIn: true,
    version: 1,
    parameters: {
      attack: 0.005,
      decay: 1.5,
      sustain: 0.3,
      release: 1.0,
      cutoff: 8000,
      resonance: 1.0,
      brightness: 0.8,
    },
  },
  {
    id: 'soft-piano',
    name: 'Soft Piano',
    instrumentId: 'acoustic-piano',
    category: 'Piano',
    isBuiltIn: true,
    version: 1,
    parameters: {
      attack: 0.04,
      decay: 2.0,
      sustain: 0.4,
      release: 1.4,
      cutoff: 2500,
      resonance: 0.8,
      brightness: 0.4,
    },
  },
  {
    id: 'bright-piano',
    name: 'Bright Piano',
    instrumentId: 'acoustic-piano',
    category: 'Piano',
    isBuiltIn: true,
    version: 1,
    parameters: {
      attack: 0.002,
      decay: 1.0,
      sustain: 0.2,
      release: 0.8,
      cutoff: 12000,
      resonance: 1.5,
      brightness: 1.0,
    },
  },

  // KEYS PRESETS
  {
    id: 'stage-epiano',
    name: 'Stage E-Piano',
    instrumentId: 'electric-piano',
    category: 'Keys',
    isBuiltIn: true,
    version: 1,
    parameters: {
      attack: 0.01,
      decay: 1.2,
      sustain: 0.5,
      release: 0.8,
      cutoff: 4000,
      resonance: 1.2,
      brightness: 0.7,
    },
  },
  {
    id: 'vintage-tines',
    name: 'Vintage Tines',
    instrumentId: 'electric-piano',
    category: 'Keys',
    isBuiltIn: true,
    version: 1,
    parameters: {
      attack: 0.02,
      decay: 1.5,
      sustain: 0.6,
      release: 1.0,
      cutoff: 3200,
      resonance: 2.0,
      brightness: 0.6,
    },
  },

  // GUITAR PRESETS
  {
    id: 'acoustic-guitar-preset',
    name: 'Acoustic Guitar',
    instrumentId: 'guitar',
    category: 'Guitar',
    isBuiltIn: true,
    version: 1,
    parameters: {
      attack: 0.01,
      decay: 0.8,
      sustain: 0.2,
      release: 0.8,
      cutoff: 5000,
      resonance: 1.5,
      brightness: 0.75,
    },
  },

  // BASS PRESETS
  {
    id: 'electric-bass',
    name: 'Electric Bass',
    instrumentId: 'bass',
    category: 'Bass',
    isBuiltIn: true,
    version: 1,
    parameters: {
      attack: 0.01,
      decay: 0.4,
      sustain: 0.6,
      release: 0.4,
      cutoff: 1500,
      resonance: 2.0,
      brightness: 0.5,
    },
  },
  {
    id: 'deep-bass',
    name: 'Deep Bass',
    instrumentId: 'bass',
    category: 'Bass',
    isBuiltIn: true,
    version: 1,
    parameters: {
      attack: 0.02,
      decay: 0.6,
      sustain: 0.7,
      release: 0.6,
      cutoff: 600,
      resonance: 1.0,
      brightness: 0.3,
    },
  },

  // SYNTH LEAD & PAD PRESETS
  {
    id: 'classic-lead',
    name: 'Classic Lead',
    instrumentId: 'synth-lead',
    category: 'Lead',
    isBuiltIn: true,
    version: 1,
    parameters: {
      attack: 0.01,
      decay: 0.3,
      sustain: 0.8,
      release: 0.4,
      cutoff: 6000,
      resonance: 3.5,
      brightness: 0.9,
    },
  },
  {
    id: 'warm-pad',
    name: 'Warm Pad',
    instrumentId: 'synth-pad',
    category: 'Pad',
    isBuiltIn: true,
    version: 1,
    parameters: {
      attack: 0.4,
      decay: 1.5,
      sustain: 0.9,
      release: 1.8,
      cutoff: 3000,
      resonance: 1.0,
      brightness: 0.5,
    },
  },
  {
    id: 'digital-pluck',
    name: 'Digital Pluck',
    instrumentId: 'pluck',
    category: 'Synth',
    isBuiltIn: true,
    version: 1,
    parameters: {
      attack: 0.001,
      decay: 0.25,
      sustain: 0.0,
      release: 0.2,
      cutoff: 7000,
      resonance: 4.0,
      brightness: 0.95,
    },
  },

  // STRINGS PRESETS
  {
    id: 'soft-strings',
    name: 'Soft Strings',
    instrumentId: 'strings',
    category: 'Strings',
    isBuiltIn: true,
    version: 1,
    parameters: {
      attack: 0.3,
      decay: 1.2,
      sustain: 0.8,
      release: 1.2,
      cutoff: 3500,
      resonance: 1.0,
      brightness: 0.6,
    },
  },
  {
    id: 'cinematic-strings',
    name: 'Cinematic Strings',
    instrumentId: 'strings',
    category: 'Strings',
    isBuiltIn: true,
    version: 1,
    parameters: {
      attack: 0.15,
      decay: 1.8,
      sustain: 0.85,
      release: 1.8,
      cutoff: 6500,
      resonance: 1.8,
      brightness: 0.85,
    },
  },

  // DRUMS PRESETS
  {
    id: 'standard-kit',
    name: 'Standard Kit',
    instrumentId: 'drum-kit',
    category: 'Drums',
    isBuiltIn: true,
    version: 1,
    parameters: {
      attack: 0.001,
      decay: 0.2,
      sustain: 0.0,
      release: 0.2,
      cutoff: 10000,
      resonance: 1.0,
      brightness: 0.7,
    },
  },
];
