import { Track, InstrumentOption } from '../types/studio';

export const DEFAULT_INSTRUMENTS: InstrumentOption[] = [
  { name: 'Grand Piano', instrument: 'Piano', iconName: 'Piano', color: '#6366f1' },
  { name: 'Acoustic Guitar', instrument: 'Guitar', iconName: 'Guitar', color: '#10b981' },
  { name: 'Electric Bass', instrument: 'Bass', iconName: 'Disc', color: '#f59e0b' },
  { name: 'Drum Kit', instrument: 'Drums', iconName: 'Drum', color: '#f43f5e' },
  { name: 'String Section', instrument: 'Strings', iconName: 'Music', color: '#8b5cf6' },
  { name: 'Brass Ensemble', instrument: 'Brass', iconName: 'Volume2', color: '#ec4899' },
  { name: 'Alto Saxophone', instrument: 'Saxophone', iconName: 'Mic', color: '#06b6d4' },
  { name: 'Synth Lead', instrument: 'Synth', iconName: 'Zap', color: '#3b82f6' },
];

export const INITIAL_DEMO_TRACKS: Track[] = [
  {
    id: 'track-1',
    name: 'Grand Piano',
    instrument: 'Piano',
    iconName: 'Piano',
    muted: false,
    solo: false,
    volume: 85,
    color: '#6366f1',
    channel: 1,
  },
  {
    id: 'track-2',
    name: 'Acoustic Guitar',
    instrument: 'Guitar',
    iconName: 'Guitar',
    muted: false,
    solo: false,
    volume: 75,
    color: '#10b981',
    channel: 2,
  },
  {
    id: 'track-3',
    name: 'Electric Bass',
    instrument: 'Bass',
    iconName: 'Disc',
    muted: false,
    solo: false,
    volume: 80,
    color: '#f59e0b',
    channel: 3,
  },
  {
    id: 'track-4',
    name: 'Drum Kit',
    instrument: 'Drums',
    iconName: 'Drum',
    muted: false,
    solo: false,
    volume: 90,
    color: '#f43f5e',
    channel: 4,
  },
  {
    id: 'track-5',
    name: 'String Section',
    instrument: 'Strings',
    iconName: 'Music',
    muted: false,
    solo: false,
    volume: 70,
    color: '#8b5cf6',
    channel: 5,
  },
];
